[tool.poetry]
name = "py-imp"
version = "0.1.0"
description = ""
authors = ["Melvin Kisten <46846457+iammelvink@users.noreply.github.com>"]
license = "GPL-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.9"
tensorflow-gpu = {url = "https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-2.10.1-cp38-cp38-win_amd64.whl"}
sktime = {extras = ["all-extras"], version = "~0.23.0"}
feature-engine = "~1.6.2"
mlxtend = "~0.22.0"
statsmodels = "~0.14.0"
ptitprince = "~0.2.6"
deepchecks = "~0.17.4"
shap = "~0.42.1"
dice-ml = "~0.10"
tsfresh = "~0.20.1"
lovelyplots = {git = "https://github.com/iammelvink/LovelyPlots"}
rich = "12.*"
pandas = "1.5.*"
skimpy = "0.0.*"
heatmapz = "~0.0.4"
xgboost = "~2.0.0"
lightgbm = "~4.1.0"
catboost = "~1.2.2"
fastprogress = "~1.0.3"
matplotx = {extras = ["all"], version = "~0.3.10"}
sweetviz = "~2.2.1"
yellowbrick = "~1.5"
autoviz = "0.1.*"
pandas-profiling = "~3.6.6"
dtale = "~3.5.0"
sketch = "~0.4.2"
watermark = "~2.4.3"
snoop = "~0.4.3"
pydot = "~1.4.2"
optuna = "~3.3.0"
joblib = "~1.3.2"
boruta = "~0.3"
borutashap = {git = "https://github.com/Ekeany/Boruta-Shap"}
shap-hypetune = "~0.2.6"
nbconvert = "~7.8.0"
adjusttext = "~0.8"
h5py = "~3.9.0"
alibi = "~0.9.4"
matplotlib = "3.7.*"
visualkeras = {git = "https://github.com/iammelvink/visualkeras"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
