@startuml "PdM_XAI_illustration"
' top to bottom direction
' left to right direction
' title "PdM and XAI illustration"
' header "PdM XAI illustration"
' !theme sketchy
' skinparam conditionStyle InsideDiamond
' skinparam conditionStyle inside
' skinparam conditionStyle diamond
skinparam ConditionEndStyle hline
skinparam monochrome true
skinparam shadowing false
skinparam roundcorner 15
skinparam linetype ortho

' skinparam Style strictuml
' skinparam Handwritten true

' !define LIGHTSTYLE
' !define DARKRED
' !include https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

left to right direction
package "Predictive Maintenance" {
  ' [Anomaly detection] --> [Predictive Maintenance]
  [Prognostics] --> [Predictive Maintenance]
  [Diagnostics] --> [Predictive Maintenance]
}

package "eXplainable Artificial Intelligence" {
  [eXplainable Artificial Intelligence] --> [Data]
  [eXplainable Artificial Intelligence] --> [Model]
  [eXplainable Artificial Intelligence] --> [Outcome]
  [eXplainable Artificial Intelligence] --> [End-user]
}

[Predictive Maintenance] --> [eXplainable Artificial Intelligence]
@enduml